NFL_CONFERENCE_AFC = "AFC"
NFL_CONFERENCE_NFC = "NFC"

NFL_CONFERENCE_NAME_AFC = "American Football Conference"
NFL_CONFERENCE_NAME_NFC = "National Football Conference"

NFL_SUBSEASON_FLAG_PRESEASON = -1
NFL_SUBSEASON_FLAG_REGULAR_SEASON = 0
NFL_SUBSEASON_FLAG_POSTSEASON = 1

NFL_SUBSEASON_PRESEASON = "Preseason"
NFL_SUBSEASON_POSTSEASON = "Postseason"
NFL_SUBSEASON_PLAYOFFS = "Playoffs"
NFL_SUBSEASON_REGULAR_SEASON = "Regular Season"

NFL_PLAYOFF_ROUND_WILDCARD = 1
NFL_PLAYOFF_ROUND_DIVISION = 2
NFL_PLAYOFF_ROUND_CHAMPIONSHIP = 3
NFL_PLAYOFF_ROUND_SUPERBOWL = 4

NFL_EVENT_FLAG_HALL_OF_FAME = -1
NFL_EVENT_FLAG_SUPERBOWL = 1
NFL_EVENT_FLAG_PRO_BOWL = 2

