MLB_LEAGUE_AL = "AL"
MLB_LEAGUE_NL = "NL"

MLB_LEAGUE_NAME_AL = "American League"
MLB_LEAGUE_NAME_NL = "National League"

mlb_leagues = {
	MLB_LEAGUE_AL: MLB_LEAGUE_NAME_AL,
	MLB_LEAGUE_NL: MLB_LEAGUE_NAME_NL
	}



MLB_SUBSEASON_FLAG_PRESEASON = -1
MLB_SUBSEASON_FLAG_REGULAR_SEASON = 0
MLB_SUBSEASON_FLAG_POSTSEASON = 1

MLB_SUBSEASON_PRESEASON = "Preseason"
MLB_SUBSEASON_SPRING_TRAINING = "Spring Training"
MLB_SUBSEASON_POSTSEASON = "Postseason"
MLB_SUBSEASON_PLAYOFFS = "Playoffs"
MLB_SUBSEASON_REGULAR_SEASON = "Regular Season"


MLB_SPRING_TRAINING_CACTUS_LEAGUE = "Cactus League"
MLB_SPRING_TRAINING_GRAPEFRUIT_LEAGUE = "Grapefruit League"



MLB_PLAYOFF_ROUND_WILDCARD = 1
MLB_PLAYOFF_ROUND_DIVISION = 2
MLB_PLAYOFF_ROUND_CHAMPIONSHIP = 3
MLB_PLAYOFF_ROUND_WORLD_SERIES = 4

MLB_EVENT_FLAG_HALL_OF_FAME = -1
MLB_EVENT_FLAG_HOME_RUN_DERBY = 1
MLB_EVENT_FLAG_ALL_STAR_GAME = 2
