NHL_CONFERENCE_EAST = "East"
NHL_CONFERENCE_WEST = "West"

NHL_CONFERENCE_NAME_EAST = "Eastern Conference"
NHL_CONFERENCE_NAME_WEST = "Western Conference"

NHL_DIVISION_ATLANTIC = "Atlantic"
NHL_DIVISION_METROPOLITAN = "Metropolitan"
NHL_DIVISION_CENTRAL = "Central"
NHL_DIVISION_PACIFIC = "Pacific"

NHL_DIVISION_NAME_ATLANTIC = "Atlantic Division"
NHL_DIVISION_NAME_METROPOLITAN = "Metropolitan Division"
NHL_DIVISION_NAME_CENTRAL = "Central Division"
NHL_DIVISION_NAME_PACIFIC = "Pacific Division"

NHL_SUBSEASON_FLAG_PRESEASON = -1
NHL_SUBSEASON_FLAG_REGULAR_SEASON = 0
NHL_SUBSEASON_FLAG_POSTSEASON = 1

NHL_SUBSEASON_PRESEASON = "Preseason"
NHL_SUBSEASON_POSTSEASON = "Postseason"
NHL_SUBSEASON_PLAYOFFS = "Playoffs"
NHL_SUBSEASON_REGULAR_SEASON = "Regular Season"
NHL_SUBSEASON_STANLEY_CUP = "Stanley Cup"

NHL_PLAYOFF_ROUND_1 = 1
NHL_PLAYOFF_ROUND_2 = 2
NHL_PLAYOFF_ROUND_3 = 3
NHL_PLAYOFF_ROUND_STANLEY_CUP = 4

NHL_EVENT_FLAG_HALL_OF_FAME = -1
NHL_EVENT_FLAG_ALL_STAR_GAME = 1
NHL_EVENT_FLAG_WINTER_CLASSIC = 2