NBA_CONFERENCE_EAST = "East"
NBA_CONFERENCE_WEST = "West"

NBA_CONFERENCE_NAME_EAST = "Eastern Conference"
NBA_CONFERENCE_NAME_WEST = "Western Conference"

NBA_SUBSEASON_FLAG_PRESEASON = -1
NBA_SUBSEASON_FLAG_REGULAR_SEASON = 0
NBA_SUBSEASON_FLAG_POSTSEASON = 1

NBA_SUBSEASON_PRESEASON = "Preseason"
NBA_SUBSEASON_POSTSEASON = "Postseason"
NBA_SUBSEASON_PLAYOFFS = "Playoffs"
NBA_SUBSEASON_REGULAR_SEASON = "Regular Season"

NBA_PLAYOFF_1ST_ROUND = 1
NBA_PLAYOFF_ROUND_QUARTERFINALS = 2
NBA_PLAYOFF_ROUND_SEMIFINALS = 3
NBA_PLAYOFF_ROUND_FINALS = 4

NBA_EVENT_FLAG_ALL_STAR_GAME = 1
NBA_EVENT_FLAG_ALL_STAR_SATURDAY_NIGHT = 2
NBA_EVENT_FLAG_3_POINT_SHOOTOUT = 3
NBA_EVENT_FLAG_SLAM_DUNK_COMPETITION = 4
NBA_EVENT_FLAG_SKILLS_CHALLENGE = 5
NBA_EVENT_FLAG_RISING_STARS_GAME = 6
NBA_EVENT_FLAG_ALL_STAR_CELEBRITY_GAME = 7
NBA_EVENT_FLAG_SHOOTING_STARS_COMPETITION = 8

